settings:
  legacy:
    force: false
    interval: 0s
schema:
- name: echo-framework
  path: .
  args:
  - server.go
  commands:
    run:
      status: true
  watcher:
    extensions:
    - go
    paths:
    - /
    ignored_paths:
    - .git
    - .realize
    - vendor
